CREATE PROCEDURE SETActualizarProducto
@ID_PRODUCTO AS VARCHAR(50),
@NOMBRE AS VARCHAR(50),
@PRECIO AS VARCHAR(50),
@DETALLE AS VARCHAR(50),
@USUARIO_MODIFICACION AS VARCHAR(50)
AS
BEGIN

UPDATE Producto SET NOMBRE = @NOMBRE,
					PRECIO = @PRECIO,
					DETALLE = @DETALLE,
					FECHA_MODIFICACION = (SELECT CONVERT (char(10), getdate(), 103)),
					USUARIO_MODIFICACION = @USUARIO_MODIFICACION
WHERE ID_PRODUCTO = @ID_PRODUCTO					

COMMIT

END