CREATE PROCEDURE SETActualizarColaborador
@ID AS VARCHAR(50),
@NOMBRE AS VARCHAR(50),
@APELLIDOPATERNO AS VARCHAR(50),
@APELLIDOMATERNO AS VARCHAR(50),
@DNI AS VARCHAR(50),
@SEXO AS VARCHAR(50),
@CORREO AS VARCHAR(50),
@CARGO AS VARCHAR(50),
@TURNO AS VARCHAR(50),
@DES_TURNO AS VARCHAR(50),
@USUARIO_MODIFICACION AS VARCHAR(50)
AS
BEGIN

UPDATE EntidadBase SET	NOMBRE = @NOMBRE,
						APELLIDOMATERNO = @APELLIDOMATERNO,
						APELLIDOPATERNO = @APELLIDOPATERNO,
						DNI = @DNI,
						SEXO = @SEXO,
						USUARIO_MODIFICACION = @USUARIO_MODIFICACION,
						FECHA_MODIFICACION = (SELECT CONVERT (char(10), getdate(), 103))
WHERE EntidadBase.ID = @ID

COMMIT

UPDATE Colaborador SET	TURNO = @TURNO,
						CARGO = @CARGO,
						DES_TURNO = @DES_TURNO
WHERE Colaborador.ID = @ID

COMMIT

UPDATE Cuenta SET	CORREO = @CORREO
WHERE CUENTA.ID = @ID

COMMIT

END